---
# @tag docker-container-prereq-all:description: Ensure all pre-requisites are installed
# @tag docker-container-prereq-gitea:description: Ensure all pre-requisites for gitea are installed
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/prereq.yml"
  tags:
    - docker-container-prereq-all
    - docker-container-prereq-gitea

# @tag docker-container-restore-all:description: Run restic restore for all restic enabled containers.
# @tag docker-container-restore-gitea:description: Run restic restore for gitea if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/restore.yml"
  tags:
    - never
    - docker-container-restore-all
    - docker-container-restore-gitea
  when:
    - docker_container_gitea_restic_enable

# @tag docker-container-setup-all:description: Run setup task for all containers.
# @tag docker-container-setup-gitea:description: Run setup task for gitea.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-gitea
    - docker-container-restore-all
    - docker-container-restore-gitea

# @tag docker-container-backup-init-all:description: Run init backup task for all container.
# @tag docker-container-backup-init-gitea:description: Run init backup task for gitea if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_init.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-gitea
    - docker-container-backup-init-all
    - docker-container-backup-init-gitea
  when:
    - docker_container_gitea_restic_enable

# @tag docker-container-remove-all:description: Remove all containers.
# @tag docker-container-remove-gitea:description: Remove gitea.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/remove.yml"
  tags:
    - never
    - docker-container-remove-all
    - docker-container-remove-gitea
    - docker-container-purge-all
    - docker-container-purge-gitea

# @tag docker-container-purge-all:description: Remove all containers and delete volume mounts.
# @tag docker-container-purge-gitea:description: Remove gitea and delete volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/purge.yml"
  tags:
    - never
    - docker-container-purge-all
    - docker-container-purge-gitea

# @tag docker-container-backup-all:description: Backup all containers' volume mounts.
# @tag docker-container-backup-gitea:description: Backup gitea volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup.yml"
  tags:
    - never
    - docker-container-backup-all
    - docker-container-backup-gitea
  when:
    - docker_container_gitea_restic_enable

# @tag docker-container-backup-list-all:description: List all containers' backups.
# @tag docker-container-backup-list-gitea:description: List gitea backups.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_list.yml"
  tags:
    - never
    - docker-container-backup-list-all
    - docker-container-backup-list-gitea
  when:
    - docker_container_gitea_restic_enable
